src/Cocorico/CoreBundle/Entity/Listing.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cocorico\CoreBundle\Entity;

use Cocorico\CoreBundle\Model\BaseListing;
use Cocorico\CoreBundle\Model\ListingOptionInterface;
use Cocorico\MessageBundle\Entity\Thread;
use Cocorico\UserBundle\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Listing
 *
 * @ORM\Entity(repositoryClass="Cocorico\CoreBundle\Repository\ListingRepository")
 *
 * @ORM\Table(name="listing",indexes={
 *    @ORM\Index(name="created_at_l_idx", columns={"createdAt"}),
 *    @ORM\Index(name="status_l_idx", columns={"status"}),
 *    @ORM\Index(name="price_idx", columns={"price"}),
 *    @ORM\Index(name="type_idx", columns={"type"}),
 *    @ORM\Index(name="min_duration_idx", columns={"min_duration"}),
 *    @ORM\Index(name="max_duration_idx", columns={"max_duration"}),
 *    @ORM\Index(name="average_rating_idx", columns={"average_rating"}),
 *    @ORM\Index(name="admin_notation_idx", columns={"admin_notation"}),
 *  })
 */
class Listing extends BaseListing
{
    use ORMBehaviors\Timestampable\Timestampable;
    use ORMBehaviors\Translatable\Translatable;

    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Cocorico\CoreBundle\Model\CustomIdGenerator")
     *
     * @var integer
     */
    private $id;

    /**
     * @Assert\NotBlank(message="assert.not_blank")
     *
     * @ORM\ManyToOne(targetEntity="Cocorico\UserBundle\Entity\User", inversedBy="listings", cascade={"persist"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity="ListingLocation", inversedBy="listing", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\JoinColumn(name="location_id", referencedColumnName="id", onDelete="CASCADE")
     *
     * @var ListingLocation
     **/
    private $location;

    /**
     * @ORM\OneToMany(targetEntity="ListingListingCategory", mappedBy="listing", cascade={"persist", "remove"}, orphanRemoval=true)//, fetch="EAGER"
     *
     */
    private $listingListingCategories;

    /**
     * For Asserts @see \Cocorico\CoreBundle\Validator\Constraints\ListingValidator
     *
     * @ORM\OneToMany(targetEntity="ListingImage", mappedBy="listing", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"position" = "asc"})
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity="ListingListingCharacteristic", mappedBy="listing", cascade={"persist", "remove"}, orphanRemoval=true) //, fetch="EAGER"
     *
     */
    private $listingListingCharacteristics;

    /**
     *
     * @ORM\OneToMany(targetEntity="ListingDiscount", mappedBy="listing", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"fromQuantity" = "asc"})
     */
    private $discounts;


    /**
     * @ORM\OneToMany(targetEntity="Booking", mappedBy="listing", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"createdAt" = "desc"})
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="Cocorico\MessageBundle\Entity\Thread", mappedBy="listing", cascade={"remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"createdAt" = "desc"})
     */
    private $threads;

    /**
     *
     * @ORM\OneToMany(targetEntity="Cocorico\CoreBundle\Model\ListingOptionInterface", mappedBy="listing", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $options;


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->listingListingCharacteristics = new ArrayCollection();
        $this->listingListingCategories = new ArrayCollection();
        $this->discounts = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->threads = new ArrayCollection();
        $this->options = new ArrayCollection();
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add characteristics
     *
     * @param  \Cocorico\CoreBundle\Entity\ListingListingCharacteristic $listingListingCharacteristic
     * @return Listing
     */
    public function addListingListingCharacteristic(ListingListingCharacteristic $listingListingCharacteristic)
    {
        $this->listingListingCharacteristics[] = $listingListingCharacteristic;

        return $this;
    }


    /**
     * Remove characteristics
     *
     * @param \Cocorico\CoreBundle\Entity\ListingListingCharacteristic $listingListingCharacteristic
     */
    public function removeListingListingCharacteristic(ListingListingCharacteristic $listingListingCharacteristic)
    {
        $this->listingListingCharacteristics->removeElement($listingListingCharacteristic);
        $listingListingCharacteristic->setListing(null);
    }

    /**
     * Get characteristics
     *
     * @return \Doctrine\Common\Collections\Collection|ListingListingCharacteristic[]
     */
    public function getListingListingCharacteristics()
    {
        return $this->listingListingCharacteristics;
    }

    /**
     * Get characteristics ordered by Group and Characteristic
     *
     * @return ArrayCollection
     */
    public function getListingListingCharacteristicsOrderedByGroup()
    {
        $iterator = $this->listingListingCharacteristics->getIterator();
        $iterator->uasort(
            function ($a, $b) {
                /**
                 * @var ListingListingCharacteristic $a
                 * @var ListingListingCharacteristic $b
                 */
                $groupPosA = $a->getListingCharacteristic()->getListingCharacteristicGroup()->getPosition();
                $groupPosB = $b->getListingCharacteristic()->getListingCharacteristicGroup()->getPosition();

                $characteristicPosA = $a->getListingCharacteristic()->getPosition();
                $characteristicPosB = $b->getListingCharacteristic()->getPosition();
                if ($groupPosA == $groupPosB) {
                    if ($characteristicPosA == $characteristicPosB) {
                        return 0;
                    }

                    return ($characteristicPosA < $characteristicPosB) ? -1 : 1;
                }

                return ($groupPosA < $groupPosB) ? -1 : 1;
            }
        );

        return new ArrayCollection(iterator_to_array($iterator));
    }

    /**
     * Add characteristics
     *
     * @param  \Cocorico\CoreBundle\Entity\ListingListingCharacteristic $listingListingCharacteristic
     * @return Listing
     */
    public function addListingListingCharacteristicsOrderedByGroup(
        ListingListingCharacteristic $listingListingCharacteristic
    ) {
        return $this->addListingListingCharacteristic($listingListingCharacteristic);
    }


    /**
     * Remove characteristics
     *
     * @param \Cocorico\CoreBundle\Entity\ListingListingCharacteristic $listingListingCharacteristic
     */
    public function removeListingListingCharacteristicsOrderedByGroup(
        ListingListingCharacteristic $listingListingCharacteristic
    ) {
        $this->removeListingListingCharacteristic($listingListingCharacteristic);
    }


    /**
     * Add category
     *
     * @param  \Cocorico\CoreBundle\Entity\ListingListingCategory $listingListingCategory
     * @return Listing
     */
    public function addListingListingCategory(ListingListingCategory $listingListingCategory)
    {
        $listingListingCategory->setListing($this);
        $this->listingListingCategories[] = $listingListingCategory;

        return $this;
    }


    /**
     * Remove category
     *
     * @param \Cocorico\CoreBundle\Entity\ListingListingCategory $listingListingCategory
     */
    public function removeListingListingCategory(ListingListingCategory $listingListingCategory)
    {
//        foreach ($listingListingCategory->getValues() as $value) {
//            $listingListingCategory->removeValue($value);
//        }

        $this->listingListingCategories->removeElement($listingListingCategory);
    }

    /**
     * Get categories
     *
     * @return \Doctrine\Common\Collections\Collection|ListingListingCategory[]
     */
    public function getListingListingCategories()
    {
        return $this->listingListingCategories;
    }


    /**
     * Set user
     *
     * @param  \Cocorico\UserBundle\Entity\User $user
     * @return Listing
     */
    public function setUser(User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Cocorico\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Add images
     *
     * @param  \Cocorico\CoreBundle\Entity\ListingImage $image
     * @return Listing
     */
    public function addImage(ListingImage $image)
    {
        $image->setListing($this); //Because the owning side of this relation is listing image
        $this->images[] = $image;

        return $this;
    }

    /**
     * Remove images
     *
     * @param \Cocorico\CoreBundle\Entity\ListingImage $image
     */
    public function removeImage(ListingImage $image)
    {
        $this->images->removeElement($image);
        $image->setListing(null);
    }

    /**
     * Get images
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Set location
     *

src/Cocorico/CoreBundle/Form/Handler/Dashboard/BookingAskerFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Entity\Booking;
use Symfony\Component\Form\Form;

/**
 * Handle Asker Dashboard Booking Form
 *
 */
class BookingAskerFormHandler extends BookingFormHandler
{
    /**
     * Save Booking.
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     * -2: Wrong Booking Status
     * -3: Refund error
     * -4: Unknown error
     */
    protected function onSuccess(Form $form)
    {
        $result = -4; //Unknown error

        /** @var Booking $booking */
        $booking = $form->getData();
        $message = $form->get("message")->getData();
        $this->threadManager->addReplyThread($booking, $message, $booking->getUser());
        //Cancel
        $type = $this->request->get('type');
        if (in_array($booking->getStatus(), Booking::$cancelableStatus)) {
            if ($type == 'cancel') {
                if ($this->bookingManager->cancel($booking)) {
                    $result = 1;
                } else {
                    $result = -3;
                }
            }
        } else {
            $result = -2;
        }

        return $result;
    }
}

src/Cocorico/CoreBundle/Form/Handler/Dashboard/BookingFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Model\Manager\BookingManager;
use Cocorico\MessageBundle\Model\ThreadManager;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Handle Booking Form
 *
 */
abstract class BookingFormHandler
{
    /** @var Request $request */
    protected $request;
    /** @var BookingManager $bookingManager */
    protected $bookingManager;
    /** @var  ThreadManager $threadManager */
    protected $threadManager;
    /** @var  int */
    protected $expirationDelay;
    /** @var  int */
    protected $acceptationDelay;

    /**
     * @param RequestStack $requestStack
     */
    public function setRequest(RequestStack $requestStack)
    {
        $this->request = $requestStack->getCurrentRequest();;
    }

    /**
     * @param BookingManager $bookingManager
     */
    public function setBookingManager(BookingManager $bookingManager)
    {
        $this->bookingManager = $bookingManager;
    }

    /**
     * @param ThreadManager $threadManager
     */
    public function setThreadManager(ThreadManager $threadManager)
    {
        $this->threadManager = $threadManager;
    }

    /**
     * Process form
     *
     * @param $form
     *
     * @return int equal to :
     * 1: Success
     * 0: if form is not submitted:
     * -1: if form is not valid
     * -2: Wrong Booking Status
     *
     */
    public function process(Form $form)
    {
        $form->handleRequest($this->request);

        if ($form->isSubmitted() && $this->request->isMethod('POST')) {
            if ($form->isValid()) {
                $result = $this->onSuccess($form);
            } else {
                $result = -1;//form not valid
            }
        } else {
            $result = 0; //Not submitted
        }

        return $result;
    }

    /**
     * To override
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     * -2:
     * -3:
     * -4: Unknown error
     */
    abstract protected function onSuccess(Form $form);


}

src/Cocorico/CoreBundle/Form/Handler/Dashboard/BookingOffererFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Entity\Booking;
use Symfony\Component\Form\Form;

/**
 * Handle Offerer Dashboard Booking Form
 *
 */
class BookingOffererFormHandler extends BookingFormHandler
{
    /**
     * Save Booking.
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     * -2: Wrong Booking Status
     * -3: Payin PreAuth error
     * -4: Unknown error
     */
    protected function onSuccess(Form $form)
    {
        $result = -4; //Unknown error

        /** @var Booking $booking */
        $booking = $form->getData();
        $message = $form->get("message")->getData();
        $this->threadManager->addReplyThread($booking, $message, $booking->getListing()->getUser());
        //Accept or refuse
        $type = $this->request->get('type');

        $canBeAcceptedOrRefused = $this->bookingManager->canBeAcceptedOrRefusedByOfferer($booking);
        if ($canBeAcceptedOrRefused) {
            if ($type == 'accept') {
                if ($this->bookingManager->pay($booking)) {
                    $result = 1;
                } else {
                    $result = -3;
                }
            } elseif ($type == 'refuse') {
                $this->bookingManager->refuse($booking);
                $result = 1;
            }
        } else {
            $result = -2;
        }

        return $result;
    }
}

src/Cocorico/CoreBundle/Form/Type/Dashboard/BookingStatusFilterType.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cocorico\CoreBundle\Form\Type\Dashboard;

use Cocorico\CoreBundle\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingStatusFilterType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'status',
                ChoiceType::class,
                array(
                    'mapped' => false,
                    /** @Ignore */
                    'label' => false,
                    'choices' => array_flip(Booking::getVisibleStatusValues()),
                    'placeholder' => 'admin.booking.status.label',
                    'translation_domain' => 'cocorico_booking',
                )
            );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);
        $resolver->setDefaults(
            array(
                'csrf_protection' => false,
                'translation_domain' => 'cocorico_booking',
            )
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'booking_status_filter';
    }
}

src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/_completion_notice.html.twig
{% trans_default_domain 'cocorico_listing' %}

{% if listing_title == 0 or listing_desc == 0 or listing_price == 0 or listing_image == 0 or listing_characteristics == 0 or profile_photo == 0 or profile_desc == 0 %}
    <div role="alert" class="alert alert-warning list-comma">
        <i class="ico exclamation">!</i>

        <p>
            {{ 'listing.edit.completion_notice'|trans }}

            {% if listing_title == 0 %}
                <span>
                {{ 'listing.edit.completion_notice_title'|trans({
                    '%listing_edit_presentation%': path('cocorico_dashboard_listing_edit_presentation', { 'id': listing_id })
                })|raw }}
                </span>
            {% endif %}

            {% if listing_desc == 0 %}
                <span>
                {{ 'listing.edit.completion_notice_desc'|trans({
                    '%listing_edit_presentation%': path('cocorico_dashboard_listing_edit_presentation', { 'id': listing_id })
                })|raw }}
                </span>
            {% endif %}

            {% if listing_price == 0 %}
                <span>
                {{ 'listing.edit.completion_notice_price'|trans({
                    '%listing_edit_price%': path('cocorico_dashboard_listing_edit_availabilities_prices', { 'listing_id': listing_id })
                })|raw }}
                </span>
            {% endif %}

            {% if listing_image == 0 %}
                <span>
                {{ 'listing.edit.completion_notice_imgage'|trans({
                    '%listing_edit_image%': path('cocorico_dashboard_listing_edit_images', { 'id': listing_id })
                })|raw }}
                </span>
            {% endif %}

            {% if listing_characteristics == 0 %}
                <span>
                {{ 'listing.edit.completion_notice_characteristics'|trans({
                    '%listing_edit_characteristic%': path('cocorico_dashboard_listing_edit_characteristic', { 'id': listing_id })
                })|raw }}
                </span>
            {% endif %}

            {% if profile_photo == 0 %}
                <span>
                {{ 'listing.edit.completion_notice_profile_photo'|trans({
                    '%profile%': path('cocorico_user_dashboard_profile_edit_about_me')
                })|raw }}
                </span>
            {% endif %}

            {% if profile_desc == 0 %}
                <span>
                {{ 'listing.edit.completion_notice_profile_desc'|trans({
                    '%profile%': path('cocorico_user_dashboard_profile_edit_about_me')
                })|raw }}
                </span>
            {% endif %}
        </p>
    </div>
{% endif %}

src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/_nav_side.html.twig
{% trans_default_domain 'cocorico_listing' %}

<!-- tabs-aside -->
<aside class="tabs-aside">
    <div class="aside-holder">
        {{ render(controller('CocoricoCoreBundle:Dashboard/Offerer/Listing:statusNavSideForm', {'listing': listing})) }}

        <!-- tabset-holder -->
        <nav class="tabset-holder">
            <a href="#" class="opener">
                <span class="hidden">opener</span>
                <i class="icon-down-open-mini"></i></a>

            <!-- nav-tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="{{ nav_side_dashboard_current == "presentation" ? 'active' : '' }}">
                    <a href="{{ path('cocorico_dashboard_listing_edit_presentation', { 'id': listing.id }) }}"
                       aria-controls="presentation" data-text="{{ 'nav.listing.presentation.link'|trans }}">
                        {{ 'nav.listing.presentation.link'|trans }}
                    </a>
                </li>
                <li role="presentation"
                    class="{{ nav_side_dashboard_current == "availabilities_prices" ? 'active' : '' }}">
                    <a href="{{ path('cocorico_dashboard_listing_edit_availabilities_prices', { 'listing_id': listing.id }) }}"
                       aria-controls="presentation" data-text="{{ 'nav.listing.price.link'|trans }}">
                        {{ 'nav.listing.price.link'|trans }}
                    </a>
                </li>
                <li role="presentation"
                    class="{{ nav_side_dashboard_current == "availabilities_status" ? 'active' : '' }}">
                    <a data-text="{{ 'nav.listing.calendar.link'|trans }}"
                       aria-controls="presentation"
                       href="{{ path('cocorico_dashboard_listing_edit_availabilities_status', { 'listing_id': listing.id }) }}">
                        {{ 'nav.listing.calendar.link'|trans }}
                    </a>
                </li>
                <li role="presentation" class="{{ nav_side_dashboard_current == "image" ? 'active' : '' }}">
                    <a data-text="{{ 'nav.listing.images.link'|trans }}"
                       aria-controls="presentation"
                       href="{{ path('cocorico_dashboard_listing_edit_images', { 'id': listing.id }) }}">
                        {{ 'nav.listing.images.link'|trans }}
                    </a>
                </li>
                <li role="presentation" class="{{ nav_side_dashboard_current == "characteristic" ? 'active' : '' }}">
                    <a data-text="{{ 'nav.listing.characteristic.link'|trans }}"
                       aria-controls="presentation"
                       href="{{ path('cocorico_dashboard_listing_edit_characteristic', { 'id': listing.id }) }}">
                        {{ 'nav.listing.characteristic.link'|trans }}
                    </a>
                </li>
                <li role="presentation" class="{{ nav_side_dashboard_current == "categories" ? 'active' : '' }}">
                    <a data-text="{{ 'nav.listing.categories.link'|trans }}"
                       aria-controls="presentation"
                       href="{{ path('cocorico_dashboard_listing_edit_categories', { 'id': listing.id }) }}">
                        {{ 'nav.listing.categories.link'|trans }}
                    </a>
                </li>
                <li role="presentation" class="{{ nav_side_dashboard_current == "location" ? 'active' : '' }}">
                    <a data-text="{{ 'nav.listing.location.link'|trans }}"
                       aria-controls="presentation"
                       href="{{ path('cocorico_dashboard_listing_edit_location', { 'id': listing.id }) }}">
                        {{ 'nav.listing.location.link'|trans }}
                    </a>
                </li>
            </ul>
        </nav>
        <div class="currency-converter white">
            {% include '@CocoricoCore/Frontend/Common/_currency_converter.html.twig' with {'close' : false} only %}
        </div>
    </div>
</aside>

src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/edit_categories.html.twig
{% extends 'CocoricoCoreBundle:Dashboard/Listing:layout.html.twig' %}

{% trans_default_domain 'cocorico_listing' %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block nav_side_dashboard -%}
    {% set nav_side_dashboard_current = 'categories' %}
    {{ parent() }}
{%- endblock %}

{% block content_dashboard -%}
    <div class="form-area">
        {{ render(controller('CocoricoCoreBundle:Dashboard/Offerer/Listing:completionNotice', {'listing': listing})) }}

        {% include 'CocoricoCoreBundle:Frontend/Common:_flash.html.twig' %}

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="info">

                <div class="form-holder">
                    <h2>{{ 'listing.edit.categories.title'|trans }}</h2>

                    <div class="form-selection">
                        {{ render(controller('CocoricoCoreBundle:Dashboard/Offerer/ListingCategoriesAjax:categoriesAjaxForm', {'listing': listing})) }}
                    </div>

                    {#Extra fields#}
                    {% include '@CocoricoCore/Dashboard/Listing/form_categories_extra.html.twig' with {'form': form} %}
                </div>
                <!-- form-holder -->
            </div>
        </div>
        <!-- tab-content -->
    </div>
{%- endblock %}


{% block javascripts %}
    {{ parent() }}
    <script>
        $(function () {

        });
    </script>
{% endblock %}

src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/edit_characteristic.html.twig
{% extends 'CocoricoCoreBundle:Dashboard/Listing:layout.html.twig' %}

{% trans_default_domain 'cocorico_listing' %}


{% block nav_side_dashboard -%}
    {% set nav_side_dashboard_current = 'characteristic' %}
    {{ parent() }}
{%- endblock %}

{% block content_dashboard -%}

    {{ form_start(form, {'attr': {'class': 'form-area'}}) }}

    <fieldset>
        <legend class="hidden">form area</legend>
        <!-- alert -->
        {{ render(controller('CocoricoCoreBundle:Dashboard/Offerer/Listing:completionNotice', {'listing': listing})) }}

        {% include 'CocoricoCoreBundle:Frontend/Common:_flash.html.twig' %}

        {{ form_errors(form) }}
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="features">
                <div class="form-block featured-block">
                    <h2>{{ 'listing.edit.characteristic.title'|trans }}</h2>
                    <strong class="sub-heading">{{ 'listing.edit.characteristic.sub_title'|trans }}</strong>
                    <!-- features-area -->
                    <div id="characteristics" class="form-block features-area">
                        {{ form_errors(form.listingListingCharacteristicsOrderedByGroup) }}
                        {% set listingCharacteristicGroup, previousListingCharacteristicGroup = "", "" %}
                        <!--@formatter:off-->
                        {% for listingListingCharacteristic in form.listingListingCharacteristicsOrderedByGroup %}
                            {% set listingCharacteristic = listingListingCharacteristic.vars.value.listingCharacteristic %}
                            {% set listingCharacteristicGroup =  listingCharacteristic.listingCharacteristicGroup.getName() %}
                            {#{{ dump(listingCharacteristic) }}#}
                            {% if listingCharacteristicGroup != previousListingCharacteristicGroup %}
                                {% if previousListingCharacteristicGroup %}
                                    {{ '</ul>' }}
                                {% endif %}
                                {{ '<ul class="col-md-4 list-unstyled features-list-new same-height-left same-height-right">' }}
                                    <li><h3>{{ listingCharacteristicGroup }}</h3></li>
                            {% endif %}
                                    <li>
                                        <label class="label">
                                            {{ listingCharacteristic.getName() }}
                                        </label>
                                        {% if listingCharacteristic.getDescription()|length %}
                                            <button title="" data-original-title="{{ listingCharacteristic.getDescription() }}" data-placement="right" data-toggle="tooltip" class="tooltip-button" type="button">?</button>
                                        {% endif %}
                                        <div class="field-holder">
                                            {{ form_widget(listingListingCharacteristic.listingCharacteristicValue, {
                                                'attr': {
                                                    'class': "no-arrow"
                                                }
                                            }) }}
                                        </div>
                                    </li>
                                    {% set previousListingCharacteristicGroup =  listingCharacteristicGroup %}
                        {% endfor %}
                        <!--@formatter:on-->
                    </div>
                </div>

                <div class="btn-block text-center">
                    <button type="submit" class="btn btn-default">{{ 'listing.save'|trans }}</button>
                </div>
            </div>
        </div>
    </fieldset>

    {{ form_end(form) }}
{%- endblock %}



{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(function () {
            jQuery('#characteristics').sameHeight({
                elements: '>*',
                flexible: true,
                multiLine: true
            });
        });
    </script>

{% endblock %}